import type { Ticket } from './types'

export const MOCK_TICKETS: Ticket[] = [
  {
    ticket_id: 'TKT-001',
    account_id: 'acc_nutricion',
    account_name: 'Nutrición Pro MX',
    titulo: 'Configurar automatización de seguimiento de leads',
    descripcion: 'Necesitamos que cuando un lead llegue por Facebook Ads, se dispare automáticamente una secuencia de emails de 5 días en GHL. Actualmente los leads caen al CRM pero nadie les escribe.',
    fecha_deseada: '2026-04-28',
    fecha_comprometida: '2026-04-25',
    prioridad: 'Alta',
    estado: 'En progreso',
    asignado_a: 'Carlos M.',
    fecha_creacion: '2026-04-17T10:30:00Z',
    notas_internas: 'Ya tenemos acceso al sub-account. El workflow base está listo, falta conectar el trigger de FB Leads.',
  },
  {
    ticket_id: 'TKT-002',
    account_id: 'acc_nutricion',
    account_name: 'Nutrición Pro MX',
    titulo: 'Página de agenda no carga en mobile',
    descripcion: 'El botón de agendar cita en la landing de nutrición no funciona en Safari iOS. Los clientes reportan que la página se queda en blanco.',
    fecha_deseada: '2026-04-22',
    prioridad: 'Alta',
    estado: 'Abierto',
    fecha_creacion: '2026-04-19T08:15:00Z',
  },
  {
    ticket_id: 'TKT-003',
    account_id: 'acc_dental',
    account_name: 'Dental Estética Cancún',
    titulo: 'Integrar WhatsApp Business API con GHL',
    descripcion: 'Queremos que todas las conversaciones de WhatsApp Business lleguen al inbox de GHL y que los agentes puedan responder desde ahí. Tenemos número de WA verificado.',
    fecha_deseada: '2026-05-05',
    fecha_comprometida: '2026-05-02',
    prioridad: 'Media',
    estado: 'Abierto',
    asignado_a: 'Bryan A.',
    fecha_creacion: '2026-04-18T14:00:00Z',
  },
  {
    ticket_id: 'TKT-004',
    account_id: 'acc_dental',
    account_name: 'Dental Estética Cancún',
    titulo: 'Subir nuevo catálogo de servicios al sitio',
    descripcion: 'Tenemos 3 nuevos tratamientos: carillas Emax, blanqueamiento Zoom y diseño de sonrisa digital. Necesitamos agregarlos a la página de servicios con fotos y precios.',
    fecha_deseada: '2026-04-21',
    prioridad: 'Baja',
    estado: 'Completado',
    fecha_creacion: '2026-04-12T09:00:00Z',
    fecha_cierre: '2026-04-16T17:30:00Z',
    asignado_a: 'Carlos M.',
  },
  {
    ticket_id: 'TKT-005',
    account_id: 'acc_fitness',
    account_name: 'FitLife Studio',
    titulo: 'Dashboard de métricas de membresías',
    descripcion: 'Necesitamos un reporte semanal automático que muestre: nuevas membresías, cancelaciones, ingresos y membresías próximas a vencer. Se puede enviar por email o Slack.',
    fecha_deseada: '2026-05-10',
    prioridad: 'Media',
    estado: 'Abierto',
    fecha_creacion: '2026-04-20T11:00:00Z',
  },
  {
    ticket_id: 'TKT-006',
    account_id: 'acc_fitness',
    account_name: 'FitLife Studio',
    titulo: 'Error en cobros recurrentes de Stripe',
    descripcion: 'Desde el viernes pasado, los cobros mensuales de membresía anual están fallando con error "card_declined" aunque las tarjetas están vigentes. Ya revisamos con Stripe y dicen que el problema es del webhook.',
    fecha_deseada: '2026-04-21',
    fecha_comprometida: '2026-04-20',
    prioridad: 'Alta',
    estado: 'En progreso',
    asignado_a: 'Bryan A.',
    fecha_creacion: '2026-04-19T16:45:00Z',
    notas_internas: 'El webhook de Stripe está apuntando a una URL deprecada. Actualizando endpoint ahora.',
  },
  {
    ticket_id: 'TKT-007',
    account_id: 'acc_inmobiliaria',
    account_name: 'Propiedades del Golfo',
    titulo: 'Crear landing page para nuevo desarrollo Los Álamos',
    descripcion: 'Nuevo desarrollo residencial en Veracruz. Necesitamos landing con: hero con video, planos descargables, formulario de interés, integración con GHL y píxel de Meta.',
    fecha_deseada: '2026-05-15',
    prioridad: 'Alta',
    estado: 'Abierto',
    fecha_creacion: '2026-04-20T09:30:00Z',
  },
  {
    ticket_id: 'TKT-008',
    account_id: 'acc_inmobiliaria',
    account_name: 'Propiedades del Golfo',
    titulo: 'SEO local para búsquedas en Veracruz',
    descripcion: 'Queremos aparecer en "casas en venta Veracruz" y "departamentos Boca del Río". Necesitamos auditoría de SEO y plan de acción.',
    fecha_deseada: '2026-04-30',
    fecha_comprometida: '2026-04-28',
    prioridad: 'Media',
    estado: 'Completado',
    fecha_creacion: '2026-04-05T10:00:00Z',
    fecha_cierre: '2026-04-18T15:00:00Z',
    asignado_a: 'Bryan A.',
  },
  {
    ticket_id: 'TKT-009',
    account_id: 'acc_spa',
    account_name: 'Spa Serenidad',
    titulo: 'Activar sistema de reseñas automáticas',
    descripcion: 'Después de cada cita, queremos enviar un mensaje de WhatsApp pidiendo reseña en Google. Si la califican 5 estrellas, redirigir a Google Maps. Si es menor, abrir formulario interno.',
    fecha_deseada: '2026-04-26',
    prioridad: 'Media',
    estado: 'Abierto',
    fecha_creacion: '2026-04-19T13:00:00Z',
  },
  {
    ticket_id: 'TKT-010',
    account_id: 'acc_nutricion',
    account_name: 'Nutrición Pro MX',
    titulo: 'Actualizar precios en todos los funnels',
    descripcion: 'Subimos precios en enero pero se nos olvidó actualizar las páginas de ventas. Hay 4 funnels activos con precios viejos.',
    fecha_deseada: '2026-04-15',
    prioridad: 'Alta',
    estado: 'Completado',
    fecha_creacion: '2026-04-10T08:00:00Z',
    fecha_cierre: '2026-04-11T12:00:00Z',
    asignado_a: 'Carlos M.',
  },
]
